version: "3"

volumes:
  postgres_data:
    driver: local
  pgadmin:
     driver: local

services:
  postgres:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    networks:
      - postgres
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - './demo:/var/lib/postgresql/data'
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    ports:
      - "80:80"
    networks:
      - postgres
    restart: always
  
networks:
  postgres:
    driver: bridge
